name: "Run mypy"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mlops_cookiecutter/requirements.txt
        pip install -r mlops_cookiecutter/requirements_tests.txt
    - name: Sort imports
      run: |
        mypy mlops_cookiecutter/
      continue-on-error: true

