name: train-my-model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://iterativeai/cml:0-dvc2-base1  # this contains the continues machine learning pipeline
    steps:
    - uses: actions/checkout@v2
    - name: cml_run
      env:
          REPO_TOKEN: $
      run: |
        pip install -r mlops_cookiecutter/requirements.txt
        
        python mlops_cookiecutter/src/models/train_model_cml.py

        # send all information to report.md that will be reported to us when the workflow finish
        cat mlops_cookiecutter/reports/classification_report.txt >> report.md
        cml-publish mlops_cookiecutter/reports/figures/confusion_matrix.png --md >> report.md
        cml-send-comment report.md