name: train-my-model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    #container:  docker://dvcorg/cml:0-dvc2-base1  # this contains the continues machine learning pipeline
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-cml@v1
    - uses: iterative/setup-dvc@v1

    #- name: Cache pip
    #  uses: actions/cache@v2
    #  with:
    #    path: ${{ steps.pip-cache.outputs.dir }}
    #    key: ${{ runner.os }}-py
    #    restore-keys: ${{ runner.os }}-py

    - name: install_requirements
      working-directory: mlops_cookiecutter/
      run: |
        pip install -r requirements.txt

    - name: create gdrive_credentials
      run: |
        echo $gdrive_credentials >> gdrive_credentials.json
        shell: bash
        env:
          gdrive_credentials: ${{secrets.GDRIVE_CREDENTIALS_DATA}}


    - name: Pull Data
      #working-directory: mlops_cookiecutter/
      run: |
        dvc init --no-scm
        # configuring remote server in dvc
        dvc remote add -d storage gdrive://1EQmnf_diOrKH0hZ9GleolN5EvgRCGjCy
        dvc remote modify storage gdrive_use_service_account true
        dvc remote modify storage gdrive_service_account_json_file_path gdrive_credentials.json

        dvc pull --run-cache


    - name: cml_run
      working-directory: mlops_cookiecutter/
      env:
          REPO_TOKEN: $
      run: |
        python src/models/train_model_cml.py

        # send all information to report.md that will be reported to us when the workflow finish
        cat reports/classification_report.txt >> report.md
        cml-publish reports/figures/confusion_matrix.png --md >> report.md
        cml-send-comment report.md