name: train-my-model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    #container:  docker://dvcorg/cml:0-dvc2-base1  # this contains the continues machine learning pipeline
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-cml@v1
    - uses: iterative/setup-dvc@v1

    - name: install_requirements
      working-directory: mlops_cookiecutter/
      run: |
        pip install -r requirements.txt

    - name: Pull Data
      #working-directory: mlops_cookiecutter/
      run: |
        dvc pull --run-cache
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
           REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: cml_run
      working-directory: mlops_cookiecutter/
      env:
          REPO_TOKEN: $
      run: |
        python src/models/train_model_cml.py

        # send all information to report.md that will be reported to us when the workflow finish
        cat reports/classification_report.txt >> report.md
        cml-publish reports/figures/confusion_matrix.png --md >> report.md
        cml-send-comment report.md